# Generated by Django 4.1 on 2022-09-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_product_availability_product_color_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_urls',
            new_name='images_urls',
        ),
    ]
