# Generated by Django 4.1 on 2022-09-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_rename_images_urls_product_image_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url_original',
        ),
    ]
