# Generated by Django 4.1 on 2022-09-15 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_customuser_contact_information_customuser_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_information',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 03xxxxxxxxx', regex='^(03)\\d{9}$')]),
        ),
    ]
