# Generated by Django 4.1 on 2022-09-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_remove_product_url_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
