# Generated by Django 4.1 on 2022-09-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_alter_customuser_contact_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='retailer_sku',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
