# Generated by Django 4.1 on 2022-09-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
